# Generated by Django 3.2.3 on 2021-06-01 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=200)),
                ('no', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('lnkdin', models.CharField(max_length=100)),
                ('brd1', models.CharField(max_length=100)),
                ('schl1', models.CharField(max_length=100)),
                ('year1', models.DateField()),
                ('percent1', models.CharField(max_length=100)),
                ('brd2', models.CharField(max_length=100)),
                ('schl2', models.CharField(max_length=100)),
                ('year2', models.DateField()),
                ('percent2', models.CharField(max_length=100)),
                ('course', models.CharField(max_length=100)),
                ('uni', models.CharField(max_length=100)),
                ('instname', models.CharField(max_length=100)),
                ('year3', models.DateField()),
                ('percent3', models.CharField(max_length=100)),
                ('beg', models.CharField(max_length=100)),
                ('prof', models.CharField(max_length=100)),
                ('suff', models.CharField(max_length=100)),
                ('topic1', models.CharField(max_length=100)),
                ('orgname1', models.CharField(max_length=100)),
                ('cityname1', models.CharField(max_length=100)),
                ('dur1', models.PositiveIntegerField()),
                ('date1', models.DateField()),
                ('date2', models.DateField()),
                ('topic2', models.CharField(max_length=100)),
                ('orgname2', models.CharField(max_length=100)),
                ('cityname2', models.CharField(max_length=100)),
                ('dur2', models.PositiveIntegerField()),
                ('date3', models.DateField()),
                ('date4', models.DateField()),
                ('profimg', models.ImageField(upload_to='profile image')),
            ],
        ),
    ]
