# Generated by Django 3.2.3 on 2021-06-01 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='desc1',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='desc2',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='projname1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='projname2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
