# Generated by Django 3.2.3 on 2021-06-01 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20210601_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='aboutme',
            field=models.TextField(null=True),
        ),
    ]
