# Generated by Django 3.2.3 on 2021-06-01 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_resume_achievements'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='skill1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='skill2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='skill3',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
