# Generated by Django 3.2.3 on 2021-06-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20210601_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='beg',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='cityname1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='cityname2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='date1',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='date2',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='date3',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='date4',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='dur1',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='dur2',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='orgname1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='orgname2',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='prof',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='suff',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='topic1',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='topic2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
