from django import forms
from .models import Resume


class ResumeForm(forms.ModelForm):
    class Meta:
        model = Resume
        fields = ['name', 'email', 'no', 'address', 'lnkdin', 'aboutme', 'brd1', 'schl1', 'year1',
                    'percent1', 'brd2', 'schl2', 'year2', 'percent2', 'course', 'uni', 'instname',
                    'year3', 'percent3', 'beg', 'prof', 'suff', 'topic1', 'orgname1', 'cityname1',
                    'dur1', 'date1', 'date2', 'topic2', 'orgname2', 'cityname2', 'dur2', 'date3',
                    'date4', 'projname1', 'projdur1', 'desc1', 'projname2', 'projdur2', 'desc2',
                    'skill1', 'skill2', 'skill3', 'achievements', 'profimg']

        labels = {'name':'Full Name', 'address':'Full Address', 'no':'Phone No.', 'email':'Email-Id',
                  'lnkdin':'LinkedIn', 'aboutme':'Career Objective', 'brd1':'10th Board', 'schl1':'School Name',
                  'year1':'Year of Joining - Year of Passing', 'percent1':'Percentage', 'brd2':'12th Board',
                  'schl2': 'School Name', 'year2': 'Year of Joining - Year of Passing', 'percent2': 'Percentage',
                  'course':'Graduation Course', 'uni':'University Name', 'instname':'College Name',
                  'year3':'Year of Joining - Year of Passing', 'percent3':'Percentage', 'beg':'Technical Skills (Beginner)',
                  'prof':'Technical Skills (Proficient)', 'suff':'Technical Skills (Sufficient Knowledge)', 'topic1':'Training (Topic 1)',
                  'orgname1':'Name of Organization', 'cityname1':'City of Organization',
                  'dur1':'Duration', 'date1':'From', 'date2':'To','topic2':'Training (Topic 2)',
                  'orgname2':'Name of Organization', 'cityname2':'City of Organization',
                  'dur2':'Duration', 'date3':'From', 'date4':'To',  'projname1':'Project Name 1',
                  'projdur1': 'Project Duration', 'desc1':'Project Description', 'projname2':'Project Name 2',
                  'projdur2':'Project Duration', 'desc2':'Project Description',
                  'skill1':'Soft Skill 1', 'skill2':'Soft Skill 2', 'skill3':'Soft Skill 3', 'achievements':'Achievements', 'profimg':'Profile Image'}

        widgets = {'name': forms.TextInput(attrs={'placeholder': 'Eg. Shivansh Kamboj'}),
                   'address': forms.TextInput(attrs={'placeholder': 'Eg. 5247, Blue av. sc 2657, City, Country'}),
                   'no': forms.TextInput(attrs={'placeholder': 'Eg. 1234567899'}),
                   'email': forms.TextInput(attrs={'placeholder': 'Eg. yourmail@gmail.com '}),
                   'lnkdin': forms.TextInput(attrs={'placeholder': 'Eg. /in/shivansh-kamboj-36120717a'}),
                   'aboutme': forms.Textarea(attrs={'cols': 50, 'rows': 3, 'placeholder': 'To associate myself with a reputed organization where I can utilize my skills to fulfil the goals & objectives of the organization and could enhance my competencies and potential.'}),
                   'brd1': forms.TextInput(attrs={'placeholder': 'Eg. CBSE, ICSE'}),
                   'schl1': forms.TextInput(attrs={'placeholder': 'Eg. ABC School, City'}),
                   'year1': forms.TextInput(attrs={'placeholder': 'Eg. 2013 - 2014'}),
                   'percent1': forms.TextInput(attrs={'placeholder': 'Eg. 99%'}),
                   'brd2': forms.TextInput(attrs={'placeholder': 'Eg. CBSE, ICSE'}),
                   'schl2': forms.TextInput(attrs={'placeholder': 'Eg. ABC School, City'}),
                   'year2': forms.TextInput(attrs={'placeholder': 'Eg. 2015 - 2016'}),
                   'percent2': forms.TextInput(attrs={'placeholder': 'Eg. 99%'}),
                   'course': forms.TextInput(attrs={'placeholder': 'Eg. B.TECH (CSE)'}),
                   'uni': forms.TextInput(attrs={'placeholder': 'Eg. Delhi University'}),
                   'instname': forms.TextInput(attrs={'placeholder': 'Eg. NSIT, Delhi'}),
                   'year3': forms.TextInput(attrs={'placeholder': 'Eg. 2018 - 2022'}),
                   'percent3': forms.TextInput(attrs={'placeholder': 'Eg. 99%'}),
                   'beg': forms.TextInput(attrs={'placeholder': 'Eg. Android, Jquery'}),
                   'prof': forms.TextInput(attrs={'placeholder': 'Eg. C, C++, Python'}),
                   'suff': forms.TextInput(attrs={'placeholder': 'Eg. Html, CSS, JS'}),
                   'topic1': forms.TextInput(attrs={'placeholder': 'Eg. Django'}),
                   'orgname1': forms.TextInput(attrs={'placeholder': 'Eg. XYZ solutions'}),
                   'cityname1': forms.TextInput(attrs={'placeholder': 'Eg. Delhi'}),
                   'dur1': forms.TextInput(attrs={'placeholder': 'Eg. 2 months'}),
                   'date1': forms.TextInput(attrs={'placeholder': 'Eg. 2020-04-15'}),
                   'date2': forms.TextInput(attrs={'placeholder': 'Eg. 2020-06-15'}),
                   'topic2': forms.TextInput(attrs={'placeholder': 'Eg. Django'}),
                   'orgname2': forms.TextInput(attrs={'placeholder': 'Eg. XYZ solutions'}),
                   'cityname2': forms.TextInput(attrs={'placeholder': 'Eg. Delhi'}),
                   'dur2': forms.TextInput(attrs={'placeholder': 'Eg. 2 months'}),
                   'date3': forms.TextInput(attrs={'placeholder': 'Eg. 2020-04-15'}),
                   'date4': forms.TextInput(attrs={'placeholder': 'Eg. 2020-06-15'}),
                   'projname1': forms.TextInput(attrs={'placeholder': 'Eg. Library Management'}),
                   'projdur1': forms.TextInput(attrs={'placeholder': 'Eg. 1 month'}),
                   'projname2': forms.TextInput(attrs={'placeholder': 'Eg. Library Management'}),
                   'projdur2': forms.TextInput(attrs={'placeholder': 'Eg. 1 month'}),
                   'skill1': forms.TextInput(attrs={'placeholder': 'Eg. Leadership'}),
                   'skill2': forms.TextInput(attrs={'placeholder': 'Eg. Teamwork'}),
                   'skill3': forms.TextInput(attrs={'placeholder': 'Eg. Time Management'}),
                   'desc1': forms.Textarea(attrs={'cols': 50, 'rows': 5, 'placeholder': 'Eg. This is a library Management project in which all the information of how many and which books are present in the library can be easily proctored. It is beneficial for both students as well as school/college.'}),
                   'desc2': forms.Textarea(attrs={'cols':  50, 'rows': 5, 'placeholder': 'Eg. This is a library Management project in which all the information of how many and which books are present in the library can be easily proctored. It is beneficial for both students as well as school/college.'}),
                   'achievements': forms.Textarea(attrs={'cols': 50, 'rows': 5, 'placeholder':'Write your achievements in about 40-50 words in the form of points.'}),

                   }



class ResumeForm2(forms.ModelForm):
    class Meta:
        model = Resume
        fields = ['name', 'email', 'no', 'address', 'lnkdin', 'aboutme', 'brd1', 'schl1', 'year1',
                  'percent1', 'brd2', 'schl2', 'year2', 'percent2', 'course', 'uni', 'instname',
                  'year3', 'percent3', 'beg', 'prof', 'suff', 'topic1', 'orgname1', 'cityname1',
                  'dur1', 'date1', 'date2', 'topic2', 'orgname2', 'cityname2', 'dur2', 'date3',
                  'date4', 'projname1', 'projdur1', 'desc1', 'projname2', 'projdur2', 'desc2',
                  'skill1', 'skill2', 'skill3', 'achievements', 'profimg']

        labels = {'name': 'Full Name', 'address': 'Full Address', 'no': 'Phone No.', 'email': 'Email-Id',
                  'lnkdin': 'LinkedIn', 'aboutme': 'Career Objective', 'brd1': '10th Board', 'schl1': 'School Name',
                  'year1': 'Year of Joining - Year of Passing', 'percent1': 'Percentage', 'brd2': '12th Board',
                  'schl2': 'School Name', 'year2': 'Year of Joining - Year of Passing', 'percent2': 'Percentage',
                  'course': 'Graduation Course', 'uni': 'University Name', 'instname': 'College Name',
                  'year3': 'Year of Joining - Year of Passing', 'percent3': 'Percentage',
                  'beg': 'Hardskill 1',
                  'prof': 'Hardskill 2', 'suff': 'Hardskill 3',
                  'topic1': 'Training (Topic 1)',
                  'orgname1': 'Name of Organization', 'cityname1': 'City of Organization',
                  'dur1': 'Duration', 'date1': 'From', 'date2': 'To', 'topic2': 'Training (Topic 2)',
                  'orgname2': 'Name of Organization', 'cityname2': 'City of Organization',
                  'dur2': 'Duration', 'date3': 'From', 'date4': 'To', 'projname1': 'Project Name 1',
                  'projdur1': 'Project Duration', 'desc1': 'Project Description', 'projname2': 'Project Name 2',
                  'projdur2': 'Project Duration', 'desc2': 'Project Description',
                  'skill1': 'Soft Skill 1', 'skill2': 'Soft Skill 2', 'skill3': 'Soft Skill 3',
                  'achievements': 'Achievements', 'profimg': 'Profile Image'}

        widgets = {'name': forms.TextInput(attrs={'placeholder': 'Eg. Shivansh Kamboj'}),
                   'address': forms.TextInput(attrs={'placeholder': 'Eg. 5247, Blue av. sc 2657, City, Country'}),
                   'no': forms.TextInput(attrs={'placeholder': 'Eg. 1234567899'}),
                   'email': forms.TextInput(attrs={'placeholder': 'Eg. yourmail@gmail.com '}),
                   'lnkdin': forms.TextInput(attrs={'placeholder': 'Eg. /in/shivansh-kamboj-36120717a'}),
                   'aboutme': forms.Textarea(attrs={'cols': 50, 'rows': 3,
                                                    'placeholder': 'To associate myself with a reputed organization where I can utilize my skills to fulfil the goals & objectives of the organization and could enhance my competencies and potential.'}),
                   'brd1': forms.TextInput(attrs={'placeholder': 'Eg. CBSE, ICSE'}),
                   'schl1': forms.TextInput(attrs={'placeholder': 'Eg. ABC School, City'}),
                   'year1': forms.TextInput(attrs={'placeholder': 'Eg. 2013 - 2014'}),
                   'percent1': forms.TextInput(attrs={'placeholder': 'Eg. 99%'}),
                   'brd2': forms.TextInput(attrs={'placeholder': 'Eg. CBSE, ICSE'}),
                   'schl2': forms.TextInput(attrs={'placeholder': 'Eg. ABC School, City'}),
                   'year2': forms.TextInput(attrs={'placeholder': 'Eg. 2015 - 2016'}),
                   'percent2': forms.TextInput(attrs={'placeholder': 'Eg. 99%'}),
                   'course': forms.TextInput(attrs={'placeholder': 'Eg. B.TECH (ME)'}),
                   'uni': forms.TextInput(attrs={'placeholder': 'Eg. Delhi University'}),
                   'instname': forms.TextInput(attrs={'placeholder': 'Eg. NSIT, Delhi'}),
                   'year3': forms.TextInput(attrs={'placeholder': 'Eg. 2018 - 2022'}),
                   'percent3': forms.TextInput(attrs={'placeholder': 'Eg. 99%'}),
                   'beg': forms.TextInput(attrs={'placeholder': 'Eg. Excellent Mental Math, Ledger Balancing'}),
                   'prof': forms.TextInput(attrs={'placeholder': 'Eg. Adaptability, Collaboration, Problem Solving'}),
                   'suff': forms.TextInput(attrs={'placeholder': 'Eg. Data Entry Skills, Cash Handling'}),
                   'topic1': forms.TextInput(attrs={'placeholder': 'Eg. Django'}),
                   'orgname1': forms.TextInput(attrs={'placeholder': 'Eg. XYZ solutions'}),
                   'cityname1': forms.TextInput(attrs={'placeholder': 'Eg. Delhi'}),
                   'dur1': forms.TextInput(attrs={'placeholder': 'Eg. 2 months'}),
                   'date1': forms.TextInput(attrs={'placeholder': 'Eg. 2020-04-15'}),
                   'date2': forms.TextInput(attrs={'placeholder': 'Eg. 2020-06-15'}),
                   'topic2': forms.TextInput(attrs={'placeholder': 'Eg. Django'}),
                   'orgname2': forms.TextInput(attrs={'placeholder': 'Eg. XYZ solutions'}),
                   'cityname2': forms.TextInput(attrs={'placeholder': 'Eg. Delhi'}),
                   'dur2': forms.TextInput(attrs={'placeholder': 'Eg. 2 months'}),
                   'date3': forms.TextInput(attrs={'placeholder': 'Eg. 2020-04-15'}),
                   'date4': forms.TextInput(attrs={'placeholder': 'Eg. 2020-06-15'}),
                   'projname1': forms.TextInput(attrs={'placeholder': 'Eg. Library Management'}),
                   'projdur1': forms.TextInput(attrs={'placeholder': 'Eg. 1 month'}),
                   'projname2': forms.TextInput(attrs={'placeholder': 'Eg. Library Management'}),
                   'projdur2': forms.TextInput(attrs={'placeholder': 'Eg. 1 month'}),
                   'skill1': forms.TextInput(attrs={'placeholder': 'Eg. Leadership'}),
                   'skill2': forms.TextInput(attrs={'placeholder': 'Eg. Teamwork'}),
                   'skill3': forms.TextInput(attrs={'placeholder': 'Eg. Time Management'}),
                   'desc1': forms.Textarea(attrs={'cols': 50, 'rows': 5,
                                                  'placeholder': 'Eg. This is a library Management project in which all the information of how many and which books are present in the library can be easily proctored. It is beneficial for both students as well as school/college.'}),
                   'desc2': forms.Textarea(attrs={'cols': 50, 'rows': 5,
                                                  'placeholder': 'Eg. This is a library Management project in which all the information of how many and which books are present in the library can be easily proctored. It is beneficial for both students as well as school/college.'}),
                   'achievements': forms.Textarea(attrs={'cols': 50, 'rows': 5,
                                                         'placeholder': 'Write your achievements in about 40-50 words in the form of points.'}),

                   }


class ResumeForm3(forms.ModelForm):
    class Meta:
        model = Resume
        fields = ['name', 'address', 'no', 'email', 'lnkdin', 'aboutme', 'brd1', 'schl1', 'year1',
                    'percent1', 'brd2', 'schl2', 'year2', 'percent2', 'course', 'uni', 'instname',
                    'year3', 'percent3', 'beg', 'suff', 'prof', 'topic1', 'orgname1',
                    'cityname1', 'date1', 'date2', 'desc1', 'topic2', 'orgname2', 'cityname2',
                    'date3', 'date4',  'desc2',
                    'skill1', 'skill2', 'skill3', 'achievements', 'profimg']

        labels = {'name':'Full Name', 'address': 'Full Address', 'no': 'Phone No.', 'email': 'Email-Id',
                  'lnkdin': 'LinkedIn', 'aboutme': 'About Me', 'brd1': 'Board', 'schl1': 'Name of School',
                  'year1': 'Year of Passing', 'percent1': 'Percentage/CGPA', 'brd2': 'Board',
                  'schl2': 'Name of School', 'year2': 'Year of Passing', 'percent2': 'Percentage/CGPA',
                  'course': 'Course', 'uni': 'University Name', 'instname': 'Name of Institute',
                  'year3': 'Year of Passing', 'percent3': 'Percentage/CGPA', 'beg': 'Hardskill 1',
                  'suff': 'Hardskill 2', 'prof': 'Hardskill 3',
                   'topic1':'Work Position 1', 'orgname1':'Name of Organization', 'cityname1':'City of Organization',
                   'date1':'From', 'date2':'To', 'desc1':'Work Description 1', 'topic2':'Work Position 2',
                  'orgname2':'Name of Organization', 'cityname2':'City of Organization',
                  'date3':'From', 'date4':'To', 'desc2':'Work Description 2',
                  'skill1':'Skill 1', 'skill2':'Skill 2', 'skill3':'Skill 3', 'achievements':'Achievements',
                  'profimg':'Profile Image'}
