from django.db import models
from django import forms


class Resume(models.Model):
    name = models.CharField(max_length=100)
    address = models.CharField(max_length=200)
    no = models.PositiveIntegerField()
    email = models.EmailField()
    lnkdin = models.CharField(max_length=100)
    aboutme = models.TextField(null=True)
    brd1 =  models.CharField(max_length=100)
    schl1 = models.CharField(max_length=100)
    year1 = models.CharField(max_length=100, null=True)
    percent1 = models.CharField(max_length=100)
    brd2 = models.CharField(max_length=100)
    schl2 = models.CharField(max_length=100)
    year2 = models.CharField(max_length=100, null=True)
    percent2 = models.CharField(max_length=100)
    course = models.CharField(max_length=100)
    uni = models.CharField(max_length=100)
    instname = models.CharField(max_length=100)
    year3 = models.CharField(max_length=100, null=True)
    percent3 = models.CharField(max_length=100)
    beg = models.CharField(max_length=100, null=True)
    prof = models.CharField(max_length=100, null=True)
    suff = models.CharField(max_length=100, null=True)
    topic1 = models.CharField(max_length=100, null=True)
    orgname1 = models.CharField(max_length=100, null=True)
    cityname1 = models.CharField(max_length=100, null=True)
    dur1 = models.CharField(max_length=100, null=True)
    date1 = models.CharField(max_length=100, null=True)
    date2 = models.CharField(max_length=100, null=True)
    topic2 = models.CharField(max_length=100, null=True)
    orgname2 = models.CharField(max_length=100, null=True)
    cityname2 = models.CharField(max_length=100, null=True)
    dur2 = models.CharField(max_length=100, null=True)
    date3 = models.CharField(max_length=100, null=True)
    date4 = models.CharField(max_length=100, null=True)
    projname1 = models.CharField(max_length=100, null=True)
    projdur1 = models.CharField(max_length=100, null=True)
    desc1 = models.TextField(null=True)
    projname2 = models.CharField(max_length=100, null=True)
    projdur2 = models.CharField(max_length=100, null=True)
    desc2 = models.TextField(null=True)
    skill1 = models.CharField(max_length=100, null=True)
    skill2 = models.CharField(max_length=100, null=True)
    skill3 = models.CharField(max_length=100, null=True)
    achievements = models.TextField(null=True)
    profimg = models.ImageField(upload_to='profile image', blank=False)

