from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.signup, name="signup"),
    path('login/', views.login, name="login"),
    path('about', views.about, name="about"),
    path('home/', views.home, name="home"),
    path('engineering', views.engineering, name="engineering"),
    path('CSEtemplates', views.csetemplates, name="csetemplates"),
    path('CEtemplates', views.cetemplates, name="cetemplates"),
    path('MEtemplates', views.metemplates, name="metemplates"),
    path('EEtemplates', views.eetemplates, name="eetemplates"),
    path('ECEtemplates', views.ecetemplates, name="ecetemplates"),
    path('BankingTemplates', views.bankingtemplates, name="BankingTemplates"),
    path('MarketingTemplates', views.marketingtemplates, name="MarketingTemplates"),
    path('TeachingTemplates', views.teachingtemplates, name="TeachingTemplates"),
    path('logout', views.logout, name="logout"),
    path('formview', views.FormView.as_view(), name="formview"),
    url('/(?P<pk>[0-9a-z-]+)/xyz', views.CandidateView.as_view(), name="candidate"),
    path('form1', views.Form1.as_view(), name="form1"),
    url('(?P<pk>[0-9a-z-]+)/xyz1', views.xyz1.as_view(), name="xyz1"),
    path('form2', views.Form2.as_view(), name="form2"),
    url('(?P<pk>[0-9a-z-]+)/xyz2', views.xyz2.as_view(), name="xyz2"),
    path('form3', views.Form3.as_view(), name="form3"),
    url('(?P<pk>[0-9a-z-]+)/xyz3', views.xyz3.as_view(), name="xyz3"),
    path('form4', views.Form4.as_view(), name="form4"),
    url('(?P<pk>[0-9a-z-]+)/xyz4', views.xyz4.as_view(), name="xyz4"),
    path('form5', views.FormCE1.as_view(), name="form5"),
    url('(?P<pk>[0-9a-z-]+)/xyz5', views.xyz5.as_view(), name="xyz5"),
    path('form6', views.FormCE2.as_view(), name="form6"),
    url('(?P<pk>[0-9a-z-]+)/xyz6', views.xyz6.as_view(), name="xyz6"),
    path('form7', views.FormCE3.as_view(), name="form7"),
    url('(?P<pk>[0-9a-z-]+)/xyz7', views.xyz7.as_view(), name="xyz7"),
    path('form8', views.FormCE4.as_view(), name="form8"),
    url('(?P<pk>[0-9a-z-]+)/xyz8', views.xyz8.as_view(), name="xyz8"),
    path('form9', views.FormCE5.as_view(), name="form9"),
    url('(?P<pk>[0-9a-z-]+)/xyz9', views.xyz9.as_view(), name="xyz9"),
    path('formME1', views.FormME1.as_view(), name="formME1"),
    url('(?P<pk>[0-9a-z-]+)/pdfME1', views.pdfME1.as_view(), name="pdfME1"),
    path('formME2', views.FormME2.as_view(), name="formME2"),
    url('(?P<pk>[0-9a-z-]+)/pdfME2', views.pdfME2.as_view(), name="pdfME2"),
    path('formME3', views.FormME3.as_view(), name="formME3"),
    url('(?P<pk>[0-9a-z-]+)/pdfME3', views.pdfME3.as_view(), name="pdfME3"),
    path('formME4', views.FormME4.as_view(), name="formME4"),
    url('(?P<pk>[0-9a-z-]+)/pdfME4', views.pdfME4.as_view(), name="pdfME4"),
    path('formME5', views.FormME5.as_view(), name="formME5"),
    url('(?P<pk>[0-9a-z-]+)/pdfME5', views.pdfME5.as_view(), name="pdfME5"),
    path('formEE1', views.FormEE1.as_view(), name="formEE1"),
    url('(?P<pk>[0-9a-z-]+)/pdfEE1', views.pdfEE1.as_view(), name="pdfEE1"),
    path('formEE2', views.FormEE2.as_view(), name="formEE2"),
    url('(?P<pk>[0-9a-z-]+)/pdfEE2', views.pdfEE2.as_view(), name="pdfEE2"),
    path('formEE3', views.FormEE3.as_view(), name="formEE3"),
    url('(?P<pk>[0-9a-z-]+)/pdfEE3', views.pdfEE3.as_view(), name="pdfEE3"),
    path('formEE4', views.FormEE4.as_view(), name="formEE4"),
    url('(?P<pk>[0-9a-z-]+)/pdfEE4', views.pdfEE4.as_view(), name="pdfEE4"),
    path('formEE5', views.FormEE5.as_view(), name="formEE5"),
    url('(?P<pk>[0-9a-z-]+)/pdfEE5', views.pdfEE5.as_view(), name="pdfEE5"),
    path('formECE1', views.FormECE1.as_view(), name="formECE1"),
    url('(?P<pk>[0-9a-z-]+)/pdfECE1', views.pdfECE1.as_view(), name="pdfECE1"),
    path('formECE2', views.FormECE2.as_view(), name="formECE2"),
    url('(?P<pk>[0-9a-z-]+)/pdfECE2', views.pdfECE2.as_view(), name="pdfECE2"),
    path('formECE3', views.FormECE3.as_view(), name="formECE3"),
    url('(?P<pk>[0-9a-z-]+)/pdfECE3', views.pdfECE3.as_view(), name="pdfECE3"),
    path('formECE4', views.FormECE4.as_view(), name="formECE4"),
    url('(?P<pk>[0-9a-z-]+)/pdfECE4', views.pdfECE4.as_view(), name="pdfECE4"),
    path('formECE5', views.FormECE5.as_view(), name="formECE5"),
    url('(?P<pk>[0-9a-z-]+)/pdfECE5', views.pdfECE5.as_view(), name="pdfECE5"),
    path('formBank1', views.FormBank1.as_view(), name="formBank1"),
    url('(?P<pk>[0-9a-z-]+)/pdfBANK1', views.pdfBANK1.as_view(), name="pdfBANK1"),
    path('formBank2', views.FormBank2.as_view(), name="formBank2"),
    url('(?P<pk>[0-9a-z-]+)/pdfBANK2', views.pdfBANK2.as_view(), name="pdfBANK2"),
    path('formBank3', views.FormBank3.as_view(), name="formBank3"),
    url('(?P<pk>[0-9a-z-]+)/pdfBANK3', views.pdfBANK3.as_view(), name="pdfBANK3"),
    path('formBank4', views.FormBank4.as_view(), name="formBank4"),
    url('(?P<pk>[0-9a-z-]+)/pdfBANK4', views.pdfBANK4.as_view(), name="pdfBANK4"),
    path('formBank5', views.FormBank5.as_view(), name="formBank5"),
    url('(?P<pk>[0-9a-z-]+)/pdfBANK5', views.pdfBANK5.as_view(), name="pdfBANK5"),


] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
